dist: freebsd

language: julia

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.7

os:
    - freebsd

julia:
    - 0.7
    - 1.0

before_script:
    - python3.7 --version
